In [1]:
#Imports
import os
import numpy as np
import pandas as pd
#plotting
import matplotlib.colors as mcolors
from matplotlib.patches import Rectangle
import plotly.express as px
import plotly.graph_objects as go
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

#import joypy
import scipy
from scipy import stats

from helpers import *

In [8]:
test_csv_1 = "/mnt/bigdisk1/AllieSpangaro/Morphology_Replicative_Age_Project/CP_Output/Apr10_2025/Apr10_test/new_masks/Cell.csv"
test_csv_2 = "/mnt/bigdisk1/AllieSpangaro/Morphology_Replicative_Age_Project/CP_Output/Apr10_2025/Apr10_test/Old_masks/Cell.csv"

cell_new = pd.read_csv(test_csv_1)
cell_old = pd.read_csv(test_csv_2)

#cell_v1.head()
clipped_new = cell_new.loc[cell_new['FileName_DAPI'] == "SUM_ch4-r05c05f01.tif"]
clipped_old = cell_old.loc[cell_old['FileName_DAPI'] == "SUM_ch4-r05c05f01.tif"]

clipped_new = clipped_new[["Metadata_Field","ObjectNumber","Children_Lysosomes_Count","Children_Mitochondria_Count","AreaShape_Area.1"]]
clipped_old = clipped_old[["Metadata_Field","ObjectNumber","Children_Lysosomes_Count","Children_Mitochondria_Count","AreaShape_Area.1"]]

display(clipped_new,clipped_old)

,Metadata_Field,ObjectNumber,Children_Lysosomes_Count,Children_Mitochondria_Count,AreaShape_Area.1
0,1,1,224,130,69804
1,1,2,391,192,107167
2,1,3,76,69,43200
3,1,4,243,136,99020
4,1,5,144,49,65540
5,1,6,454,300,240280
6,1,7,782,740,406505
7,1,8,340,190,166305
8,1,9,476,295,189072

,Metadata_Field,ObjectNumber,Children_Lysosomes_Count,Children_Mitochondria_Count,AreaShape_Area.1
0,1,1,213,128,68848
1,1,2,333,166,83615
2,1,3,87,77,49152
3,1,4,263,163,99648
4,1,5,116,48,58896
5,1,6,138,97,43584
6,1,7,559,619,326881
7,1,8,332,260,186897
8,1,9,274,166,110808
9,1,10,287,190,138425
10,1,11,448,289,172152

In [3]:
test_csv_1 = "/mnt/bigdisk1/AllieSpangaro/Morphology_Replicative_Age_Project/CP_Output/Mar28_2025/v1/Cell.csv"
test_csv_2 = "/mnt/bigdisk1/AllieSpangaro/Morphology_Replicative_Age_Project/CP_Output/Mar28_2025/test4/Cell.csv"

cell_v1 = pd.read_csv(test_csv_1)
cell_old = pd.read_csv(test_csv_2)

#cell_v1.head()
clipped_v1 = cell_v1.loc[cell_v1['FileName_DAPI'] == "SUM_ch4-r02c02f20.tif"]
cell_v1.loc
clipped_old = cell_old.loc[cell_old['FileName_DAPI'] == "SUM_ch4-r02c02f20.tif"]


display(clipped_v1,clipped_old)

,ImageNumber,ObjectNumber,Metadata_CellSizeFlag,Metadata_ChannelNumber,Metadata_EmptyImage_Cells,Metadata_EmptyImage_Nuclei,Metadata_Field,Metadata_FileLocation,Metadata_Frame,Metadata_Series,...,Texture_Variance_RescaleIntensityDAPI_3_02_256,Texture_Variance_RescaleIntensityDAPI_3_03_256,Texture_Variance_RescaleIntensityLAMP1_3_00_256,Texture_Variance_RescaleIntensityLAMP1_3_01_256,Texture_Variance_RescaleIntensityLAMP1_3_02_256,Texture_Variance_RescaleIntensityLAMP1_3_03_256,Texture_Variance_RescaleIntensityMito_3_00_256,Texture_Variance_RescaleIntensityMito_3_01_256,Texture_Variance_RescaleIntensityMito_3_02_256,Texture_Variance_RescaleIntensityMito_3_03_256
129,60,1,0,NaN,0,0,NaN,NaN,0,0,...,364.797317,367.649317,163.759259,164.902443,166.320235,164.919634,103.237228,103.691863,103.875246,103.695638

,ImageNumber,ObjectNumber,Metadata_ChannelNumber,Metadata_Field,Metadata_FileLocation,Metadata_Frame,Metadata_Series,Metadata_Well,Metadata_WellColumn,Metadata_WellRow,...,Texture_Variance_RescaleIntensityDAPI_3_02_256,Texture_Variance_RescaleIntensityDAPI_3_03_256,Texture_Variance_RescaleIntensityLAMP1_3_00_256,Texture_Variance_RescaleIntensityLAMP1_3_01_256,Texture_Variance_RescaleIntensityLAMP1_3_02_256,Texture_Variance_RescaleIntensityLAMP1_3_03_256,Texture_Variance_RescaleIntensityMito_3_00_256,Texture_Variance_RescaleIntensityMito_3_01_256,Texture_Variance_RescaleIntensityMito_3_02_256,Texture_Variance_RescaleIntensityMito_3_03_256
70,20,1,NaN,20,NaN,0,0,B02,2,2,...,571.076374,570.374903,163.878567,165.400898,166.925655,162.940599,101.596616,101.587016,101.560545,101.649312